### PR TITLE
fix: scan only currently watching when scan_whole_list is disabled

### PR DESCRIPTION
**Pull request by serjflint**
Relates: #598

### CODE REVIEW

**Review by FichteFoll — APPROVED** [review]

**Comment by z411** [comment]
This was the original behavior. This was changed because people wanted also to scan on hold and plan to watch lists as well, as they usually don't have a lot of results in them either.

**Comment by serjflint** [comment]
@z411 they can use "Scan through whole list" for that, though.

**Comment by z411** [comment]
> @z411 they can use "Scan through whole list" for that, though.

Scan through whole list also scans through Finished, which is most of the time, a ton. This PR removes a feature that was requested. In that case we could add three options: Scan only watching, scan usual lists (watching, on hold, plan_to_watch), scan everything (edge case, probably).

**Comment by serjflint** [comment]
@z411 I agree. The option to choose what to scan is better. That's why I called this PR 'a dirty hack' in the [discussion](https://github.com/z411/trackma/issues/598#issuecomment-1019214648)  =)

**Comment by FichteFoll** [comment]
> Scan only watching, scan usual lists (watching, on hold, plan_to_watch), scan everything (edge case, probably).

Would making the list of statuses to scan configurable be feasible? That would certainly be the most flexible options and I think also be more transparent for the user since the current behavior even confused me in the code (i.e. what do `statuses_library`, `statuses`, and `statuses_library` mean exactly?).

**Comment by serjflint** [comment]
@FichteFoll better move to the related [issue](https://github.com/z411/trackma/issues/598). I closed this PR and we need a new one to solve the issue the way you mentioned.

**Pull request closed without merging**
