### PR TITLE
[Engine+Qt] Fixes

### PR DESCRIPTION
**Pull request by ahmubashshir**
Engine:
 * support external function for creating detached process
 
Qt:
 * Launch player using `QtCore.QProcess`

### CODE REVIEW

**Comment by ahmubashshir** [comment]
I think this will fix #525

**Comment by z411** [comment]
This issue made me think about this but, instead of passing a custom function to the engine, maybe it would be better for the user interface to handle starting processes. The engine can just return the process and the arguments (or just the filename?) and the actual starting could be handled by the user interface. This is already the case for opening links for example.

**Comment by ahmubashshir** [comment]
> This issue made me think about this but, instead of passing a custom function to the engine, maybe it would be better for the user interface to handle starting processes. The engine can just return the process and the arguments (or just the filename?) and the actual starting could be handled by the user interface. This is already the case for opening URLs for example.

We can define a signal handler for launching player with a default handler. Then engine will call connected signal handler with `player` and `filename` args.

**Comment by z411** [comment]
Thanks for your work. I modified this so the spawning of subprocesses is handled by the UIs as I said. Sadly, the problem still isn't fixed. Does it work at all for you? It works for me on Qt only, but the double fork method (I moved it to `utils.py`) does nothing for me. I pushed to the `ahmubashshir-prevent-zombie` branch.

**Comment by z411** [comment]
Thanks for your work. I modified this so the spawning of subprocesses is handled by the UIs as I said.

Sadly, the problem still isn't fixed. Does it work at all for you? It works for me on Qt only, but the double fork method (I moved it to utils.py) does nothing.

**Comment by ahmubashshir** [comment]
Didn't tried yet. I'll notify when I try it :)

**Pull request merged**
