### PR TITLE
open containing folder (gtk ui)

### PR DESCRIPTION
**Pull request by anjandev**
Added open containing folder button to gtk ui as discussed in #133. The button opens the folder containing the anime with whatever file manager the user has as default and displays an error if no folder is found.

As @MadeOfMagicAndWires recommended, I opened a new PR (and closed #208) to keep the git commit logs clean. Special thanks to @MadeOfMagicAndWires for helping me out. I will try working on adding this function to the qt and cli uis.

### CODE REVIEW

**Comment by anjandev** [comment]
@z411 what do you think of this?

**Comment by z411** [comment]
Looks fine, although I'd do 2 things before merging:

1. The library is in an usable state now, so it'd be much faster to use that instead of searching for the episode path each time, since the library already has the full paths of all available episodes on disk. I'll migrate the engine.play_episode routine to use the library too, and hopefully deprecate the engine._search_video routine altogether.
2. Is it necessary to use a separate thread for this?

**Comment by z411** [comment]
Done (https://github.com/z411/trackma/commit/bf2d5aa7dc1a86735424aa0a27c2615d7361d788).

Now you should be able to use the engine.get_episode_path function to get the full path of the episode from the library. So just something like:

    filename = self.get_episode_path(show, 1)

should be enough.

**Comment by MadeOfMagicAndWires** [comment]
I'll work on it and make another clean pull with the conflicts resolved as well.

(Really wish Github could handle a pull request using rebase instead of merge all the time...)

**Comment by z411** [comment]
Superseded by #247

**Pull request closed without merging**
