### PR TITLE
Use sorted and  filtered global ListStore and implement #177 in Gtk UI.

### PR DESCRIPTION
**Pull request by ahmubashshir**
* Created ShowList class which is a child class of Gtk.TreeModelSort.
 * Used ShowList to wrap Gtk.TreeModelFilter which wraps Gtk.ListStore.
 * Implemented required methods in ShowList.
 * Implemented #177.

### CODE REVIEW

**Comment by ahmubashshir** [comment]
@FichteFoll,@z411 can you review these changes, please?

**Comment by FichteFoll** [comment]
I don't have any expertise with this part of the code, nor with Gtk, so I'll refrain from reviewing. I did take a brief look, though.

**Comment by ahmubashshir** [comment]
> I don't have any expertise with this part of the code, nor with Gtk, so I'll refrain from reviewing. I did take a brief look, though.

Then can you test and notify me if you find any bugs, please?

**Comment by z411** [comment]
Great, a global filtered ListStore is the way to go for this and it's something I always wanted to do and it reaches feature parity with the Qt interface. I plan to go back to development soon so I'll take a look as soon as I can. Thanks for your work.

**Comment by fushinari** [comment]
I tested it and it works perfectly for me.

**Comment by ahmubashshir** [comment]
> I tested it and it works perfectly for me.
> 
> Edit: Can you make the number of entries optional?

Ok.

**Comment by fushinari** [comment]
> Ok. btw, I tried to follow the qt ui.

I like that it's there. I just don't find myself needing it. I feel like that information should be presented elsewhere but I don't know where either.

**Comment by ahmubashshir** [comment]
@fushinari should I add a field 8n ui-gtk.json for this?

**Comment by fushinari** [comment]
I personally would've liked that but I'm not sure how other would feel. Right now, tab scrolling is disabled, so the window size becomes fixed (at around 920px for me with the counters and even without that, it was fixed at around 620 or so). Even with the tab scrolling enabled, it will become fixed at around 570px. And that would've been great if Notebook wasn't wasting space just because scrolling is enabled.

I tried enabling GtkNotebook's tab scrolling:

Screenshot from 2020-10-21 01-05-09

I don't know if it's better or worse tbh... I'll leave that up to you ig. I'm fine with that myself though.

**Comment by z411** [comment]
The window indeed gets too wide, so I think tab scrolling is a good idea.

**Comment by ahmubashshir** [comment]
@z411 @fushinari enabled scrolling in GtkNotebook(with mouse scroll support).

**Comment by ahmubashshir** [comment]
BTW, @fushinari anime is shown twice in ui. Shouldn't it appear in only subtitle?

image

**Comment by fushinari** [comment]
Oh, sorry I missed that. But yeah it's redundant, you could remove it.

**Comment by z411** [comment]
Thank you.

**Comment by FichteFoll** [comment]
The individual tabs seem to become unnecessarily large when the window is too small, but that's padding is only added when not all tabs can fit into the window and made so that the tabs that didn't make it aren't cut off, so this is fine to me. The most important tabs are at the front anyway.

**Pull request merged**
