### PR TITLE
Make play_episode work with multi-episode files

### PR DESCRIPTION
**Pull request by awlayton**
Hopefully these changes aren't horrendous or anything.

1. Changes `_search_video` to look for a file ***containing*** `episode` rather than only one ***ending*** with `episode`
1. Changes `play_episode` to return the last episode of the played file

### CODE REVIEW

**Comment by Argon-** [comment]
Does this work with e.g. `Psycho-Pass 2 - 02.mkv` (or whatever other combination of multiple numbers)?

**Comment by awlayton** [comment]
The logic and regexs for parsing the range of episodes from the filename was already there, this just makes use of that.

It detects that file as episode 2 of the show `"Psycho-Pass 2"`.

**Comment by z411** [comment]
This breaks Play Next for some reason.

**Comment by awlayton** [comment]
Play next works for me.

**Comment by awlayton** [comment]
What UI are you using? I might have only tested the changes in the CLI.

**Comment by z411** [comment]
Using a different UI shouldn't have any effect, but I'm also using the CLI.
I just noticed it happening so I haven't looked at the code yet, but some examples of what's happening:

    z411@MyAnimeList(anime) Watching> play 5
    Engine: Searching for Rolling☆Girls 10...
    Engine: Found. Starting player...
    Playing: /mnt/wing/Torrent/anime/[Commie] The Rolling Girls - 06 [61155F8C].mkv

    z411@MyAnimeList(anime) Watching> play "Junketsu no Maria" 9
    Engine: Searching for Junketsu no Maria 9...
    Engine: Found. Starting player...
    Playing: /mnt/wing/Torrent/anime/[HorribleSubs] Maria the Virgin Witch - 07 [720p].mkv

    z411@MyAnimeList(anime) Watching> play "Death Parade" 8
    Engine: Searching for Death Parade 8...
    Engine: Found. Starting player...
    Playing: /mnt/wing/Torrent/anime/[FFF] Death Parade - 04 [E62A11C3].mkv

**Comment by awlayton** [comment]
Dang I see a problem with the episode range check. I'll fix it when I get to my desk.

**Pull request merged**
