### PR TITLE
GH Pages Improvements

### PR DESCRIPTION
**Pull request by alsoGAMER**
Various improvements for the gh-pages project page

### CODE REVIEW

**Comment by alsoGAMER** [comment]
@z411 could you please take a look?

**Comment by z411** [comment]
Thanks for the work! Although I'd prefer to keep the old screenshots for now. They surely need updating, but I like them having a different theme (from their respective DE usually) to show the difference. If you could please remove the screenshots from this PR I'll merge the rest.

**Comment by alsoGAMER** [comment]
@z411 Done. I'm keeping the new ones on my local machine just in case you need them anyway.

**Comment by z411** [comment]
Great, thank you!

**Pull request merged**
