### PR TITLE
[Qt,Utils] Play consolidation; purge account db button

### PR DESCRIPTION
**Pull request by Birdulon**
Combined "Play" and "Play Next" buttons into a button menu which defaults to Play Next and additionally has "Play Episode..." for playing arbitrary episode numbers. Added sorting on the percent column of the shows table, and a context menu containing a subset of the Show menu.
Added a Purge button to the account manager for discarding stale dbs (mostly for #163).

### CODE REVIEW

**Comment by Birdulon** [comment]
Added progress/percent widget color selection, fixed colors updating on settings dialog cancellation, added a nested dict update in parse_config to maintain compatibility with older configs that lack the additional color fields.

**Comment by Birdulon** [comment]
(Inspired by #153) Added an EpisodeBar style which overlays the episode sub bar onto a standard-looking ProgressBar to keep closer to the Qt widget style look. Added relevant settings to allow choice of the standard ProgressBar, the current dual bar or this new dual bar. Settings dialog started to get too tall so I moved the EpisodeBar and Color settings to a new tab.

**Comment by z411** [comment]
Thank you for your work. I'll be merging most of this, but before merging I'd like to comment a few points:

1. Instead of having a numeric entry dialog to specify the episode to play, what about generating he popup menu according to the number of episodes? The GTK does this when you right-click a show in the list.
2. I don't use KDE and don't get any icons, so we should probably provide stock icons. I've wanted this for some time anyway because I wanted to add a toolbar, and icons always make a GUI look better.
3. About the purge button; purging the database can already be done automatically by bumping the version variable in the data.py file (line 40). Should we still provide manual purging?

I can do most of these changes, don't worry.

**Comment by Birdulon** [comment]
1) sounds good to me, I was thinking of doing that before I got bogged down
in what to do with shows that have hundreds of episodes (Gintama) and went
with numeric entry as an easy out.

2) yep yep

3) I didn't know that. From a developer standpoint a manual button is nice
but if it's useless to users it could be omitted or concealed.

Cheers

**Comment by z411** [comment]
Okay thanks, merged.

**Pull request merged**
