### PR TITLE
fix 'Using Plex' spam introduced in the refactoring

### PR DESCRIPTION
**Pull request by Hairo**

### CODE REVIEW

**Comment by z411** [comment]
I don't use Plex but why is the second "Using plex" message (the one in the while loop) necessary? Shouldn't the first one be enough?

**Comment by Hairo** [comment]
It's there in case of connection issues, it's displayed when it reconnects back to the plex server, though i could change it to say "Reconnected to plex" or something.

**Comment by z411** [comment]
That would be better. Just that and I'll merge.

**Comment by z411** [comment]
Thanks.

**Pull request merged**
