### PR TITLE
Added screenshot for Gtk3.

### PR DESCRIPTION
**Pull request by ahmubashshir**

### CODE REVIEW

**Comment by FichteFoll** [comment]
[COMIC SAAAAAAANS!](http://explosm.net/comics/2301/)

**Comment by dyskette** [comment]
I'd prefer to see a screenshot with the stock gnome 3.32 theme and fonts

**Comment by z411** [comment]
Thank you. I'd also agree with @dyskette - if you can provide it with a regular/default font and theme I'll merge. It also seems he's planning to redesign the main screen in the future.

I also think the rest of the interfaces need new screenshots but I'm not running a DE right now and my environment looks bad.

**Comment by dyskette** [comment]
Yes, I'm planning a redesign, but it will take me a while. In the meantime, if the screenshots are updated to the current state of the UI, it's fine.

**Comment by ahmubashshir** [comment]
Is this ok?
screen_gtk

Setting | Value
:---|:---
Theme|Adwaita
Icon|Adwaita
Font|Cantarell

**Comment by dyskette** [comment]
Yeah, that should be fine.

**Comment by ahmubashshir** [comment]
New PR #432

**Pull request closed without merging**
