### PR TITLE
WIP: Gtk refactor and HeaderBars

### PR DESCRIPTION
**Pull request by dyskette**
So, I had a long weekend and did some work on Trackma Gtk.

This is pretty much a work in progress of the [mockups I made a long time ago](https://github.com/z411/trackma/issues/365#issuecomment-435704848). The main window is still mostly the same, but I've made some changes to the rest of the windows.

It is using [pygi-composite-templates](https://github.com/virtuald/pygi-composite-templates) with glade files. GtkApplicationWindow and GtkAction were introduced for the appmenu.

Decoupling the main window from everything was cumbersome, but I think is mostly done. The next step would be to improve this and fix bugs introduced. Tray is probably broken. And reimplement shortcuts. Yeah, sorry.

Much more later, I want to experiment with new lists views using GtkListBox, but that would be until I have some more days free.

__Screenshots__
Captura de pantalla de 2019-04-21 14-26-16

- [accounts window](https://user-images.githubusercontent.com/6687927/56474603-a8d9ab00-6441-11e9-9f81-dfb95071f490.png)
- [mediatype menu](https://user-images.githubusercontent.com/6687927/56474468-df162b00-643f-11e9-92ca-5006dfe3b2f9.png)
- [application menu](https://user-images.githubusercontent.com/6687927/56474469-df162b00-643f-11e9-8d4c-9b6b6c0ffc6b.png)
- [search window](https://user-images.githubusercontent.com/6687927/56474470-df162b00-643f-11e9-90b6-d1f7c5073543.png)
- [settings window (1)](https://user-images.githubusercontent.com/6687927/56474471-dfaec180-643f-11e9-8a6f-fadda5333077.png)
- [settings window (2)](https://user-images.githubusercontent.com/6687927/56474472-dfaec180-643f-11e9-837e-c45c215a461e.png)
- [settings window (3)](https://user-images.githubusercontent.com/6687927/56474473-dfaec180-643f-11e9-858b-6e8dc03884f9.png)
- [about window](https://user-images.githubusercontent.com/6687927/56474474-dfaec180-643f-11e9-8e8b-73d22ff00a93.png)

### CODE REVIEW

**Comment by z411** [comment]
Impressive work you've done here; the Qt has been slowly getting refactored and revamped so the GTK was in urgent need of care as well. Just one thing, it seems there's a control missing in the Settings panel, can you check that?

```
File ".../trackma/ui/gtk/settingswindow.py", line 187, in _load_config
    self.spinbutton_upload_off.set_active(True)
AttributeError: 'SettingsWindow' object has no attribute 'spinbutton_upload_off'
```

**Comment by dyskette** [comment]
Done. I missed the widget name.

**Comment by z411** [comment]
It's working, thanks again for your work, it's highly appreciated.

**Comment by FichteFoll** [comment]
```
~ ∇ trackma-gtk
Trackma-gtk v0.8.1
Traceback (most recent call last):
  File "/usr/bin/trackma-gtk", line 11, in <module>
    load_entry_point('Trackma==0.8.1', 'gui_scripts', 'trackma-gtk')()
  File "/usr/lib/python3.7/site-packages/trackma/ui/gtk/main.py", line 45, in main
    app.main()
  File "/usr/lib/python3.7/site-packages/trackma/ui/gtk/window.py", line 77, in main
    self._create_engine(manager.get_default())
  File "/usr/lib/python3.7/site-packages/trackma/ui/gtk/window.py", line 129, in _create_engine
    self._update_widgets(account)
  File "/usr/lib/python3.7/site-packages/trackma/ui/gtk/window.py", line 188, in _update_widgets
    if self.statusicon and self.config['tray_api_icon']:
AttributeError: 'TrackmaWindow' object has no attribute 'config'
```
Looks like it may still need some attention.

**Comment by dyskette** [comment]
Yeah, that looks like a typo, should be `self._config`.

#406 Should fix it.

**Pull request merged**
