### PR TITLE
Fixes and enhancements for Gtk UI

### PR DESCRIPTION
**Pull request by ahmubashshir**
* Added 'response' handler to close AboutDialog
   * Set transient parent for trackma.ui.gtk.mainview.MainView._prompt_update_next.dialog
   * Stop search if search_entry is empty
   * Implemented #177 in Gtk UI
   * Set Widgets sensitive after completing tasks.

### CODE REVIEW

**Comment by z411** [comment]
Looks good.

One thing: Regarding #177 - I haven't touched GTK in ages so I'm not sure, but isn't it possible to have just one single liststore for all the shows and have them filtered in real-time by status (like in the Qt interface) instead of having duplicate liststores and widgets like it is now?

**Comment by ahmubashshir** [comment]
ok,I'll try to do that.

**Comment by ahmubashshir** [comment]
> Looks good.
> 
> One thing: Regarding #177 - I haven't touched GTK in ages so I'm not sure, but isn't it possible to have just one single liststore for all the shows and have them filtered in real-time by status (like in the Qt interface) instead of having duplicate liststores and widgets like it is now?

I'm closing this and opening #481.  I'll try to fix #177 in a new PR.

**Comment by ahmubashshir** [comment]
> Looks good.
> 
> One thing: Regarding #177 - I haven't touched GTK in ages so I'm not sure, but isn't it possible to have just one single liststore for all the shows and have them filtered in real-time by status (like in the Qt interface) instead of having duplicate liststores and widgets like it is now?

Implemented in #497

**Pull request closed without merging**
