### PR TITLE
Gtk and Qt5 Flatpaks

### PR DESCRIPTION
**Pull request by thebitstick**
I've tested the Gtk Flatpak, Qt5 Flatpak untested.

### CODE REVIEW

**Comment by lionirdeadman** [comment]
Master is probably not a good idea since it's a moving target.

**Comment by thebitstick** [comment]
I tried changing the base to experimental but there was quite a difference in commits, would it be possible to create a flatpak branch?

**Comment by lionirdeadman** [comment]
I meant for `org.gnome.Platform`, should've specified, haha.

**Comment by thebitstick** [comment]
oh

**Pull request closed without merging**
