### PR TITLE
[Gtk] Configurable show and progress widget colors

### PR DESCRIPTION
**Pull request by Birdulon**
Adds color selection for show text and the components of the progress/percent widget to the settings dialog. No theme-aware colors so not a true fix for #153 but it should be of some use to Gtk users.

### CODE REVIEW

**Comment by z411** [comment]
Thank you.

**Comment by archnous** [comment]
Thanks, much better. Is a 'use theme widgets/colours' option still under consideration?

**Comment by Birdulon** [comment]
I'm all for bringing the Gtk theming up to parity with the current Qt client, I'll give it a shot when I have time.

**Comment by archnous** [comment]
Latest git snapshot with "Classic Progress Bar" option working smoothly here. The API icon in tray was a nice addition too. You guys rock!

**Comment by archnous** [comment]
As of trackma-git-0.4.r88.gff0f439 the shows are neither visible nor mouse-selectable (GTK-only issue). The keyboard arrow keys however do work. This happens regardless of the user interface settings.

shot1
shot2

**Comment by z411** [comment]
@archnous If you run it through the terminal, do you get any output or error?

**Comment by archnous** [comment]
Nothing of interest:

```
% trackma-gtk 
Data: Locking database...
Data: Reading metadata...
Data: Reading queue...
Data: Reading info DB...
Data: No items in queue.
libhb: Logging in...
libhb: Downloading list...
Data: Saving info DB...
Data: Saving cache...
Data: Saving metadata...
Tracker: Initializing...
Tracker: Enabling tracker...
Tracker: Using inotify.
Tracker: inotify: Watching /storage/Anime
...
```

**Comment by z411** [comment]
@archnous I spotted the bug, please re-pull the latest commit and it should work.

**Comment by archnous** [comment]
Ah, thanks. The latest commit fixed the issue, however it broke the theme's progress bars.

shot3

**Pull request merged**
